### ISSUE TITLE
batch process

### ISSUE THREAD

**Issue by DavichiHug** [robertgallup/bmp2hex#1]
it's great tool for me . I really hope add batch process and support output text file in the future.

**Comment by robertgallup** [comment]
Great! Glad you can use it. I removed the batch shell script because bmp2hex now supports multiple files for input. This works better than the shell script did (you can process all of the bmp files in a directory with one bmp2hex command as shown in the current readme). And, output to a text file is easily accomplished by redirecting standard output (you can see this in Example 3).
